#!/usr/bin/env php
<?php
/**
 * Nuber.io
 * Copyright 2020 - 2021 Jamiel Sharief.
 *
 * SPDX-License-Identifier: AGPL-3.0
 *
 * @copyright   Copyright (c) Jamiel Sharief
 * @link        https://www.nuber.io
 * @license     https://opensource.org/licenses/AGPL-3.0 AGPL-3.0 License
 */
require dirname(__DIR__) . '/config/bootstrap.php';

use Origin\Console\ConsoleApplication;
use App\Console\Command\Update\SetupNetworkingCommand;

$app = new ConsoleApplication();
$app->name('database');
$app->description([
    'Internal update'
]);
$app->addCommand('update', SetupNetworkingCommand::class);

exit($app->run());
